version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
    commit-message:
      prefix: "chore"
      prefix-scope: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    assignees:
      - "ervardaan"
    reviewers:
      - "ervardaan"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
